name: sum_types_tutorial
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Matej Resetar <mattresetar@resocoder.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  sum_types: ^0.1.5+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  sum_types_generator: ^0.1.5+1
  build_runner:
